position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7
  state_publish_rate: 50
  action_monitor_rate: 20
  stop_trajectory_duration: 0.5
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.01
    $(arg arm_id)_joint1: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint2: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint3: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint4: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint5: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint6: {trajectory: 0.10, goal: 0.02}
    $(arg arm_id)_joint7: {trajectory: 0.10, goal: 0.02}
